apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: vkyc
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
